### registration
POST http://localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "hojiakbarandaqulov11@gmail.com",
  "password": "1234"
}

### login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "hojiakbarandaqulov11@gmail.com",
  "password": "1234"
}

### verification
GET http://localhost:8080/api/v1/auth/verification/13
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY3MTgxOTQsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcwNjM3OTQsImlzcyI6IkNob3BhciJ9.RPac80mucLTPqbUIEW44TxOktS0fTiFpMnW0oaKbbjV8k6_NVcTR2q7KWc9AgLLW6oPoAaOPPansePfkNzWbPg

### resend
GET http://localhost:8080/api/v1/auth/resend/codeuz91@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjU4MTI0NzAsImlkIjoxLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcyNjE1ODA3MCwiaXNzIjoiQ2hvcGFyIn0.t9-TUdnY2kVNOh5hbxTqS1HD1E2Hh55eLLqAhheO0WGDjNp7v5ml0nKb5InTEMSpVEhLFmHo9RSApgujTvwtMA
