###
POST http://localhost:8080/api/v1/order/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY4NDc4MjUsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcxOTM0MjYsImlzcyI6IkNob3BhciJ9.la3GMk9imF9v5MiioMgb-sd2AGRzCgVcSIBrOpf5Ak7qcbINjJiKKmvWrB83MMjkF-bsz-eteDGYGJlLPGDTKw

{
  "productId": 1,
  "amount": 100,
  "profileId": 2,
  "deliveredAddress": "Jizzax Baxmal",
  "deliveredContact": 995092376,
  "status": "preparin"
}


###
GET http://localhost:8080/api/v1/order/status/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY4NDc4MjUsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcxOTM0MjYsImlzcyI6IkNob3BhciJ9.la3GMk9imF9v5MiioMgb-sd2AGRzCgVcSIBrOpf5Ak7qcbINjJiKKmvWrB83MMjkF-bsz-eteDGYGJlLPGDTKw

###
GET http://localhost:8080/api/v1/order/byId/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY4NDc4MjUsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcxOTM0MjYsImlzcyI6IkNob3BhciJ9.la3GMk9imF9v5MiioMgb-sd2AGRzCgVcSIBrOpf5Ak7qcbINjJiKKmvWrB83MMjkF-bsz-eteDGYGJlLPGDTKw



###
GET http://localhost:8080/api/v1/order/Id/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY4NDc4MjUsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcxOTM0MjYsImlzcyI6IkNob3BhciJ9.la3GMk9imF9v5MiioMgb-sd2AGRzCgVcSIBrOpf5Ak7qcbINjJiKKmvWrB83MMjkF-bsz-eteDGYGJlLPGDTKw

###
GET http://localhost:8080/api/v1/order/orderId/10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY4NDc4MjUsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcxOTM0MjYsImlzcyI6IkNob3BhciJ9.la3GMk9imF9v5MiioMgb-sd2AGRzCgVcSIBrOpf5Ak7qcbINjJiKKmvWrB83MMjkF-bsz-eteDGYGJlLPGDTKw


###
GET http://localhost:8080/api/v1/order/orderIdStatus/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY4NDc4MjUsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcxOTM0MjYsImlzcyI6IkNob3BhciJ9.la3GMk9imF9v5MiioMgb-sd2AGRzCgVcSIBrOpf5Ak7qcbINjJiKKmvWrB83MMjkF-bsz-eteDGYGJlLPGDTKw


###
PUT http://localhost:8080/api/v1/order/update/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY4NDc4MjUsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcxOTM0MjYsImlzcyI6IkNob3BhciJ9.la3GMk9imF9v5MiioMgb-sd2AGRzCgVcSIBrOpf5Ak7qcbINjJiKKmvWrB83MMjkF-bsz-eteDGYGJlLPGDTKw

{
  "productId": 6,
  "amount": 100,
  "profile": 2,
  "deliveredAddress": "Jizzax Baxmal",
  "deliveredContact": 995092376,
  "status": "preparin"
}

###
GET http://localhost:8080/api/v1/order/list/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY4NDc4MjUsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcxOTM0MjYsImlzcyI6IkNob3BhciJ9.la3GMk9imF9v5MiioMgb-sd2AGRzCgVcSIBrOpf5Ak7qcbINjJiKKmvWrB83MMjkF-bsz-eteDGYGJlLPGDTKw

###
GET http://localhost:8080/api/v1/order/pagination?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY5MzY1ODgsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcyODIxODgsImlzcyI6IkNob3BhciJ9.r89UmsgK_R-CQ3RKcAhEu3zmia4eUbEtRI1AEj2z2wKSxYGYP3M_D9jY7wmcWcvfdrSYzXPuVoVsUnDviWnlGA


###
GET http://localhost:8080/api/v1/order/filter?
    page=1&
    size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjY5MzY1ODgsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXF1bG92NUBnbWFpbC5jb20iLCJleHAiOjE3MjcyODIxODgsImlzcyI6IkNob3BhciJ9.r89UmsgK_R-CQ3RKcAhEu3zmia4eUbEtRI1AEj2z2wKSxYGYP3M_D9jY7wmcWcvfdrSYzXPuVoVsUnDviWnlGA
